version: "3"
volumes:
  beep-data:
  beep-data-export:
services:
  beep-database:
    image: docker.io/postgres:15-alpine
    container_name: beep-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=beep
      - POSTGRES_USER=beep
      - POSTGRES_PASSWORD=beep
    volumes:
      - beep-data:/var/lib/postgresql/data
      - beep-data-export:/export
